[formatting]
align_entries = true
column_width = 120
reorder_arrays = true
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "build-dependencies",
    "dependencies",
    "dev-dependencies",
    "workspace.dependencies",
]

[rule.formatting]
reorder_keys = true
