[bans]
multiple-versions = "deny"
deny = [{ name = "openssl" }]
skip = []
skip-tree = [
    # duplicates
    "dashmap",
    "thiserror",
    "wasi",
    "windows-sys",
]

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = ["Apache-2.0", "LGPL-2.1", "MIT"]

exceptions = [
    { allow = ["BSD-3-Clause"], name = "bindgen" },
    { allow = ["ISC"], name = "libloading" },
    { allow = ["Unicode-3.0"], name = "unicode-ident" },


    # btleplug
    { allow = ["BSD-3-Clause"], name = "jni-utils" },
]
